development:
  auth0_domain: dev-orpbwu12xsj5rk0r.us.auth0.com
  auth0_client_id: RHZwtB162UI6SgI0coR8mbgQa4BoBpo3
  auth0_client_secret: 4-b_hIRGtMW82oOwy126oH2V3GZiURu0RpPdWRrlSFwewCGT6-a8oVxMi7X6P0gw
